apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: test-app
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  egress:
    # Allow DNS
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow access to kube-system for service discovery
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
---
# Добавить для внешнего доступа
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-external-to-nginx
  namespace: test-app
spec:
  podSelector:
    matchLabels:
      app: nginx
  ingress:
    - {} # Allow all ingress to nginx
  policyTypes:
    - Ingress

