apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: test-app
data:
  PORT: "3000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_NAME: "testdb"
