apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: test-app
type: Opaque
data:
  DB_USER: cG9zdGdyZXM= # base64 для 'postgres'
  DB_PASSWORD: cGFzc3dvcmQ= # base64 для 'password'
