apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: test-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 для 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # base64 для 'password'
  POSTGRES_DB: dGVzdGRi # base64 для 'testdb'
