apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: test-app
data:
  REDIS_HOST: redis.test-app.svc.cluster.local
  REDIS_PORT: "6379"
  DB_HOST: postgres.test-app.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: appdb
  PORT: "3000"
