apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-alerts
  namespace: monitoring
spec:
  groups:
    - name: example
      rules:
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High CPU usage detected
            description: "{{ $labels.instance }} has CPU usage above 80% for 5 minutes."
        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High memory usage detected
            description: "{{ $labels.instance }} has memory usage above 80% for 5 minutes."
        - alert: PodNotRunning
          expr: kube_pod_status_phase{phase!="Running"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Pod not running
            description: "{{ $labels.pod }} in namespace {{ $labels.namespace }} is not running."
