apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-app-sa
  namespace: test-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-app
  name: test-app-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-app-binding
  namespace: test-app
subjects:
  - kind: ServiceAccount
    name: test-app-sa
    namespace: test-app
roleRef:
  kind: Role
  name: test-app-role
  apiGroup: rbac.authorization.k8s.io
